{{- if .Values.aws.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cloud-manager-operator
  namespace: {{ .Values.aws.cloudManager.namespace }}
{{ include "rhai-on-xks-chart.imagePullSecrets" . }}
{{- end }}
