apiVersion: v2
name: rhai-on-xks-chart
description: RHAI on XKS Helm chart for non-OLM installation on non-OpenShift Kubernetes services (Azure, CoreWeave).
type: application
version: 3.5.0-ea.2
appVersion: 3.5.0-ea.2
