{{- if .Values.enabled }}
{{- if include "rhai-on-xks-chart.imagePullSecretEnabled" . }}
{{- $namespaces := (include "rhai-on-xks-chart.kubernetesEngineDependencyNamespaces" (dict "root" . "managedOnly" true) | fromJson).items }}
{{- if $namespaces }}
{{- $hookAnnotations := dict "helm.sh/hook" "pre-install,pre-upgrade" "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded" }}
{{ include "rhai-on-xks-chart.imagePullSecretResource" (dict "root" . "namespace" .Release.Namespace "annotations" $hookAnnotations) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhai-pre-install-namespaces-hook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rhai-on-xks-chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhai-pre-install-namespaces-hook
  labels:
    {{- include "rhai-on-xks-chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhai-pre-install-namespaces-hook
  labels:
    {{- include "rhai-on-xks-chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhai-pre-install-namespaces-hook
subjects:
  - kind: ServiceAccount
    name: rhai-pre-install-namespaces-hook
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
